### ISSUE TITLE
Fallback for editing breaks auto-population when adding content

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/nodereference_url#1]
When I enable the option "Use fallback behavior when editing content" in my node reference field, I'm able to change the value when editing, as expected. Unfortunately, with the "fallback on edit" option enabled, the node reference field doesn't get auto-populated anymore when adding new content. Instead, the field on the `node/add` form is empty.

**Comment by olafgrabienski** [comment]
@herbdool Are you using the module, and can you confirm the issue? I've already searched the Drupal queue of the module but I guess I didn't find anything. There's one similar issue which I don't really understand, though: https://www.drupal.org/project/nodereference_url/issues/2418845

**Comment by herbdool** [comment]
@olafgrabienski does this fix it? https://github.com/backdrop-contrib/nodereference_url/commit/2625c41899f512598c9e2ffbab0838bda9a18be0

You can test the dev version.

**Comment by olafgrabienski** [comment]
@herbdool Many thanks for the commit! Indeed, it fixes the issue for me. Tested with both widgets (autocomplete and select).

**Comment by herbdool** [comment]
Great! And thanks for reporting.
